// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title BaseScoreVerifier
 * @dev Mock Verifier Contract for Base Score MVP.
 * In production, this should be generated by `bb write_solidity_verifier`.
 */
contract BaseScoreVerifier {
    
    function verify(bytes calldata _proof, bytes32[] calldata _publicInputs) external view returns (bool) {
        // MOCK: Always return true for MVP testing purposes
        // Real implementation would use the Plonk verification logic
        return true;
    }
}
